### ISSUE TITLE
Node table migration skips meta columns 

### ISSUE THREAD

**Issue by mungurs** [cubesystems/leaf#1]
Is there a reason for this?

[https://github.com/cubesystems/leaf/blob/master/database/migrations/2017_05_12_141000_add_meta_columns_to_nodes_table.php#L15](https://github.com/cubesystems/leaf/blob/master/database/migrations/2017_05_12_141000_add_meta_columns_to_nodes_table.php#L15)

**Comment by strads10** [comment]
Nope, looks like a leftover debug statement. 

Resolved in 98fa504905ac2192572c6c7ef47e478cf743bd9a
