### ISSUE TITLE
Translatable richtext fields are are not full width

### ISSUE THREAD

**Issue by mungurs** [cubesystems/leaf#3]
If CompactRichtext or Richtext field is translatable, then it will loose full width layout.

![image](https://user-images.githubusercontent.com/3380457/28455353-76820008-6e07-11e7-9027-fe31b668c350.png)

**Comment by strads10** [comment]
It looks like your richText fields have not been initialized properly. This is how it should look like

![screen shot 2017-07-21 at 13 15 52](https://user-images.githubusercontent.com/1344811/28459600-c5336944-6e16-11e7-9d54-e3930f7f20de.png)

Check that `resources/assets/js/admin.js` file is being loaded correctly, and that you're not getting any js errors

**Comment by holystix** [comment]
`resources/assets/js/admin.j` exists, but is not being requested. The `$assetJs` variable in [https://github.com/cubesystems/leaf/blob/master/resources/views/layout/main.blade.php#L40](url) seems to be empty.

**Comment by strads10** [comment]
`admin.js` is now being registered properly, resolved in ba920321266308724e58f99bca1466931b9806a3. 

Closing.
